// Mocks generated by Mockito 5.4.4 from annotations
// in up_todo_app/test/data/data_source/local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:up_todo_app/data/helpers/local_database_helper.dart' as _i4;
import 'package:up_todo_app/data/requests/requests.dart' as _i6;
import 'package:up_todo_app/data/responses/responses.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllTodosByUserIdResponse_1 extends _i1.SmartFake
    implements _i3.GetAllTodosByUserIdResponse {
  _FakeGetAllTodosByUserIdResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatabaseHelper extends _i1.Mock
    implements _i4.LocalDatabaseHelper {
  MockLocalDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<_i2.Database> initDatabase() => (super.noSuchMethod(
        Invocation.method(
          #initDatabase,
          [],
        ),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.method(
            #initDatabase,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<void> addTodoToLocal(_i6.AddTodoRequestBody? addTodoRequestBody) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTodoToLocal,
          [addTodoRequestBody],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTodoFromLocal(int? todoID) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoFromLocal,
          [todoID],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> editTodoInLocal(
          _i6.UpdateTodoRequestBody? updateTodoRequestBody) =>
      (super.noSuchMethod(
        Invocation.method(
          #editTodoInLocal,
          [updateTodoRequestBody],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.GetAllTodosByUserIdResponse> getAllTodosFromLocal() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTodosFromLocal,
          [],
        ),
        returnValue: _i5.Future<_i3.GetAllTodosByUserIdResponse>.value(
            _FakeGetAllTodosByUserIdResponse_1(
          this,
          Invocation.method(
            #getAllTodosFromLocal,
            [],
          ),
        )),
      ) as _i5.Future<_i3.GetAllTodosByUserIdResponse>);

  @override
  _i5.Future<void> saveTodosFromRemoteToLocal(
          _i3.GetAllTodosByUserIdResponse? getAllTodosByUserIdResponse) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTodosFromRemoteToLocal,
          [getAllTodosByUserIdResponse],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDatabase() => (super.noSuchMethod(
        Invocation.method(
          #deleteDatabase,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
